#!/usr/bin/env python3
"""Fetch Yahoo Finance RSS for portfolio tickers and write assets/news.js."""
import json
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone, timedelta
from email.utils import parsedate_to_datetime
from html import unescape
from pathlib import Path
from urllib.parse import urlparse

TICKERS = ["RDW", "ENPH", "SOUN", "CPER"]
RSS_URL = "https://feeds.finance.yahoo.com/rss/2.0/headline?s={t}&region=US&lang=en-US"
BKK = timezone(timedelta(hours=7))
OUT = Path(__file__).resolve().parent.parent / "assets" / "news.js"

SOURCE_MAP = {
    "finance.yahoo.com": "Yahoo Finance",
    "www.yahoo.com": "Yahoo Finance",
    "www.fool.com": "Motley Fool",
    "fool.com": "Motley Fool",
    "www.marketbeat.com": "MarketBeat",
    "www.benzinga.com": "Benzinga",
    "www.investors.com": "Investor's Business Daily",
    "www.barchart.com": "Barchart",
    "simplywall.st": "Simply Wall St",
    "www.trefis.com": "Trefis",
}


def fetch(ticker: str) -> list[dict]:
    req = urllib.request.Request(
        RSS_URL.format(t=ticker), headers={"User-Agent": "Mozilla/5.0"}
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    root = ET.fromstring(data)
    items = []
    for item in root.iter("item"):
        title = (item.findtext("title") or "").strip()
        link = (item.findtext("link") or "").strip()
        pub_str = (item.findtext("pubDate") or "").strip()
        if not (title and link and pub_str):
            continue
        try:
            pub = parsedate_to_datetime(pub_str)
        except (TypeError, ValueError):
            continue
        if pub.tzinfo is None:
            pub = pub.replace(tzinfo=timezone.utc)
        host = urlparse(link).netloc
        items.append(
            {
                "ticker": ticker,
                "source": SOURCE_MAP.get(host, host),
                "summary": unescape(title),
                "href": link,
                "_pub": pub,
            }
        )
    return items


def label_for(offset: int) -> str:
    if offset == 0:
        return "วันนี้"
    if offset == 1:
        return "เมื่อวาน"
    if offset < 7:
        return f"{offset} วันก่อน"
    if offset < 14:
        return "1 สัปดาห์ก่อน"
    if offset < 30:
        return f"{offset // 7} สัปดาห์ก่อน"
    return f"~{offset // 30} เดือนก่อน"


def main() -> None:
    all_items: list[dict] = []
    for t in TICKERS:
        try:
            all_items.extend(fetch(t))
            print(f"  {t}: ok")
        except Exception as e:
            print(f"  {t}: FAILED {e}")

    seen = set()
    deduped = []
    for it in all_items:
        if it["href"] in seen:
            continue
        seen.add(it["href"])
        deduped.append(it)
    deduped.sort(key=lambda x: x["_pub"], reverse=True)

    by_date: dict[str, list[dict]] = {}
    for it in deduped:
        d = it["_pub"].astimezone(BKK).date().isoformat()
        by_date.setdefault(d, []).append(it)

    today = datetime.now(BKK).date()
    days = []
    for date_str in sorted(by_date.keys(), reverse=True):
        d = datetime.fromisoformat(date_str).date()
        offset = (today - d).days
        items = [
            {k: v for k, v in it.items() if not k.startswith("_")}
            for it in by_date[date_str]
        ]
        days.append(
            {
                "offset": offset,
                "label": label_for(offset),
                "date": date_str,
                "items": items,
            }
        )

    payload = {
        "lastUpdated": datetime.now(BKK).isoformat(timespec="seconds"),
        "source": "Yahoo Finance RSS",
        "days": days,
    }

    header = (
        "// Auto-generated by .github/workflows/update-news.yml\n"
        "// Yahoo Finance RSS — headline EN, คลิกดูรายละเอียดบน Yahoo\n"
    )
    body = "window.NEWS_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    OUT.write_text(header + body, encoding="utf-8")
    print(f"Wrote {OUT} — {len(deduped)} items across {len(days)} days")


if __name__ == "__main__":
    main()
